//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
